name: Vercel Production Deployment
on:
  workflow_call:
    secrets:
      VERCEL_ORG_ID:
        required: true
      VERCEL_TOKEN:
        required: true
      VERCEL_PROJECT_ID:
        description: 'Project ID of the vercel project you want to deploy'
        required: true
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest
      - name: Install install project
        run: pnpm i
      - name: Pull Vercel Environment Information
        run: VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID}} VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID}} vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
