name: integration
on: push
permissions:
  # Required to checkout the code
  contents: read
  # Required to put a comment into the pull-request
  pull-requests: write

jobs:
  prettier:
    uses: ./.github/workflows/prettier.yaml

  test:
    needs: [prettier]
    uses: ./.github/workflows/test.yaml

  build:
    needs: [test]
    uses: ./.github/workflows/build.yaml

  deploy-sudoku:
    needs: [build]
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yaml
    secrets:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_SUDOKU_PROJECT_ID}}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN}}

  deploy-musique:
    needs: [build]
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yaml
    secrets:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_MUSIQUE_PROJECT_ID}}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN}}
