name: pnpm test
on:
  push:
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      # Cache .pnpm-store
      - name: Cache .pnpm-store
        uses: actions/cache@v3
        with:
          path: /home/runner/setup-pnpm/node_modules/.bin/store/v3
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile  --prefer-offline
      - name: Run build
        run: pnpm build
      - name: 'Test'
        run: npx vitest --coverage.enabled --coverage.provider=v8 --coverage.reporter=json-summary --coverage.reporter=json
      - name: 'Report Coverage'
        if: always() # Also gepnpnerate the report if tests are failing
        uses: davelosert/vitest-coverage-report-action@v2
