name: test
on:
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Use Node.js 20
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        with:
          node-version: 20.5
          cache: 'pnpm'
      # Cache .pnpm-store
      - name: Cache .pnpm-store
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: /home/runner/setup-pnpm/node_modules/.bin/store/v3
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile  --prefer-offline
      - name: 'Test'
        run: npx vitest --coverage.enabled --coverage.provider=v8 --coverage.reporter=json-summary --coverage.reporter=json
      - name: 'Report Coverage'
        if: always() # Also gepnpnerate the report if tests are failing
        uses: davelosert/vitest-coverage-report-action@fa4d510c186fb4ade39d4abc751385ed72a244f1 # v2
